const targets = [
  ['/', 'Calculadoras financieras gratuitas en España'],
  ['/ahorro-inversion/', 'Calculadoras de ahorro e inversión'],
  ['/ahorro-inversion/200-euros-5-porciento-10-anos/', '200 € al mes al 5 % durante 10 años'],
  ['/ahorro-inversion/ahorrar-200-euros-mes/', 'Ahorrar 200 € al mes'],
  ['/ahorro-inversion/ahorrar-300-euros-mes/', 'Qué pasa si ahorro 300 € al mes'],
  ['/ahorro-inversion/ahorrar-500-euros-mes/', 'Qué pasa si ahorro 500 € al mes'],
  ['/ahorro-inversion/aportaciones-periodicas/', 'Calcular aportaciones mensuales'],
  ['/ahorro-inversion/calculadora-inflacion/', 'Calcular inflación y poder adquisitivo'],
  ['/ahorro-inversion/escenarios/ahorrar-10000-euros/', 'Cómo ahorrar 10.000 euros'],
  ['/ahorro-inversion/escenarios/ahorrar-100-euros-mes/', 'Ahorrar 100 euros al mes'],
  ['/ahorro-inversion/interes-compuesto/', 'Calcular interés compuesto mensual'],
  ['/ahorro-inversion/interes-simple/', 'Calcular interés simple anual'],
  ['/ahorro-inversion/objetivo-ahorro/', 'Calcular objetivo de ahorro mensual'],
  ['/ahorro-inversion/roi/', 'Calcular ROI de una inversión'],
  ['/blog/', 'Blog de finanzas personales en España'],
  ['/blog/categoria/', 'Categorías del blog de finanzas'],
  ['/blog/categoria/fiscalidad/', 'Consejos fiscales para la renta'],
  ['/blog/categoria/vivienda/', 'Consejos financieros para vivienda'],
  ['/blog/euribor-septiembre-2026/', 'Cómo afecta el Euríbor a la hipoteca'],
  ['/blog/hipoteca-vs-alquiler-2026/', 'Hipoteca o alquiler en 2026'],
  ['/blog/novedades-irpf-renta-2026/', 'Qué revisar en la declaración de la Renta 2026'],
  ['/calculadoras/', 'Calculadoras gratis online'],
  ['/calculadoras/descuento/', 'Calcular descuento y precio final'],
  ['/calculadoras/porcentaje/', 'Calcular un porcentaje de cantidad'],
  ['/calculadoras/subida-salarial/', 'Calcular una subida salarial'],
  ['/coche/', 'Calculadoras de costes del coche'],
  ['/coche/coste-por-kilometro/', 'Calcular coste por kilómetro del coche'],
  ['/coche/coste-viaje/', 'Calcular coste de viaje en coche'],
  ['/coche/coste-viaje-500-km/', 'Coste de un viaje de 500 km en gasolina'],
  ['/coche/coste-viaje-gasolina/', 'Calculadora de coste de viaje en gasolina'],
  ['/comparadores/', 'Comparadores financieros para decidir'],
  ['/comparadores/ahorrar-300-vs-500-euros/', 'Ahorrar 300 o 500 euros al mes'],
  ['/comparadores/ahorrar-vs-invertir/', 'Ahorrar o invertir dinero cada mes'],
  ['/comparadores/amortizar-cuota-vs-plazo/', 'Amortizar hipoteca: reducir cuota o reducir plazo'],
  ['/comparadores/hipoteca-20-vs-30-anos/', 'Hipoteca a 20 o 30 años: qué cambia'],
  ['/comparadores/interes-simple-vs-compuesto/', 'Interés simple o compuesto para invertir'],
  ['/comparadores/iva-anadido-vs-incluido/', 'IVA añadido o IVA incluido: cómo distinguirlos'],
  ['/comparadores/prestamo-5-vs-7-anos/', 'Préstamo a 5 o 7 años: cuota y coste'],
  ['/comparadores/salario-35-vs-40-horas/', 'Salario con jornada de 35 o 40 horas'],
  ['/escenarios/', 'Escenarios financieros con ejemplos'],
  ['/glosario/', 'Glosario de términos financieros'],
  ['/glosario/amortizacion/', 'Qué es la amortización en finanzas'],
  ['/glosario/cuota-mensual/', 'Qué es la cuota mensual en finanzas'],
  ['/glosario/euribor/', 'Qué es el Euríbor en finanzas'],
  ['/glosario/inflacion/', 'Qué es la inflación en finanzas'],
  ['/glosario/interes-compuesto/', 'Qué es el interés compuesto en finanzas'],
  ['/glosario/irpf/', 'Qué es el IRPF en finanzas'],
  ['/glosario/itp/', 'Qué es el ITP en finanzas'],
  ['/glosario/iva/', 'Qué es el IVA en finanzas'],
  ['/glosario/rentabilidad/', 'Qué es la rentabilidad en finanzas'],
  ['/glosario/roi/', 'Qué es el ROI en finanzas'],
  ['/glosario/tae/', 'Qué es la TAE en finanzas'],
  ['/glosario/tin/', 'Qué es el TIN en finanzas'],
  ['/guias/', 'Guías para calcular tus finanzas'],
  ['/guias/amortizar-hipoteca/', 'Amortizar hipoteca: reducir cuota o plazo'],
  ['/guias/calcular-cuota-hipoteca/', 'Cómo calcular la cuota de una hipoteca'],
  ['/guias/calcular-descuento/', 'Cómo calcular un descuento'],
  ['/guias/calcular-porcentaje/', 'Cómo calcular un porcentaje'],
  ['/guias/como-ahorrar-10000-euros/', 'Cómo ahorrar 10.000 €'],
  ['/guias/coste-por-kilometro/', 'Cómo calcular el coste por kilómetro de un coche'],
  ['/guias/coste-real-coche/', 'Cuál es el coste real de tener un coche'],
  ['/guias/inflacion-y-poder-adquisitivo/', 'Inflación y poder adquisitivo'],
  ['/guias/interes-compuesto/', 'Cómo funciona el interés compuesto'],
  ['/guias/salario-por-hora/', 'Cómo calcular tu salario por hora'],
  ['/guias/tae-vs-tin/', 'TAE vs TIN: ¿qué diferencia hay?'],
  ['/herramientas/', 'Todas las herramientas financieras'],
  ['/impuestos/', 'Calculadoras de impuestos en España'],
  ['/impuestos/calculadora-irpf/', 'Calculadora de IRPF 2025'],
  ['/impuestos/calculadora-iva/', 'Calcular IVA añadido o incluido'],
  ['/impuestos/calculadora-iva-21-por-ciento/', 'Calculadora de IVA del 21 %'],
  ['/impuestos/escenarios/iva-10-por-ciento/', 'IVA del 10 %'],
  ['/impuestos/escenarios/iva-4-por-ciento/', 'IVA del 4 %'],
  ['/nomina/', 'Calculadoras de nómina y salario'],
  ['/nomina/escenarios/salario-35-horas/', 'Salario por hora con jornada de 35 horas'],
  ['/nomina/salario-30000-40-horas/', 'Salario de 30.000 € con 40 horas semanales'],
  ['/nomina/salario-por-hora/', 'Calcular salario bruto por hora'],
  ['/nomina/salario-por-hora-40-horas/', 'Salario por hora con una jornada de 40 horas'],
  ['/prestamos/', 'Calculadoras de préstamos personales'],
  ['/prestamos/amortizacion-anticipada/', 'Calcular amortización anticipada'],
  ['/prestamos/calculadora-cuota-prestamo/', 'Calcular cuota de préstamo fijo'],
  ['/prestamos/cuota-prestamo-5000-euros/', 'Cuota de un préstamo de 5.000 euros'],
  ['/prestamos/escenarios/prestamo-10000-5-anos/', 'Préstamo de 10.000 € a 5 años'],
  ['/prestamos/escenarios/prestamo-20000-5-anos/', 'Préstamo de 20.000 € a 5 años'],
  ['/prestamos/prestamo-15000-5-anos/', 'Préstamo de 15.000 € a 5 años'],
  ['/prestamos/prestamo-20000-7-anos/', 'Préstamo de 20.000 € a 7 años'],
  ['/vivienda/', 'Calculadoras para comprar vivienda'],
  ['/vivienda/calculadora-hipoteca/', 'Calcular cuota de hipoteca mensual'],
  ['/vivienda/cuota-hipoteca-20-anos/', 'Calculadora de hipoteca a 20 años'],
  ['/vivienda/cuota-hipoteca-30-anos/', 'Calculadora de hipoteca a 30 años'],
  ['/vivienda/escenarios/hipoteca-100000-30-anos/', 'Hipoteca de 100.000 € a 30 años'],
  ['/vivienda/escenarios/hipoteca-150000-30-anos/', 'Hipoteca de 150.000 € a 30 años'],
  ['/vivienda/escenarios/hipoteca-200000-30-anos/', 'Hipoteca de 200.000 € a 30 años'],
  ['/vivienda/hipoteca-250000-30-anos/', 'Hipoteca de 250.000 € a 30 años'],
  ['/vivienda/hipoteca-300000-30-anos/', 'Hipoteca de 300.000 € a 30 años'],
  ['/vivienda/rentabilidad-alquiler/', 'Calcular rentabilidad de alquiler'],
];

export const seoTargets = targets.map(([href, primaryKeyword]) => ({
  href,
  primaryKeyword,
  intent: 'informacional',
  priority: 'media',
  cluster: href.split('/').filter(Boolean)[0] ?? 'portada',
}));
